### ISSUE TITLE
Installation (cortibutor type) on Windows 10

### ISSUE THREAD

**Issue by 42sol-eu** [partcad/partcad#130]
I can not get PartCAD and PartCAD-CLI installed without errors using the version 0.5.11.
(using VS Code Insider Build or VS Code ) 
This errors were thrown with Python 3.10 and 3.11

I used a clean conda environment. (Maybe conda could be the cause of the issue? Or is it the requirements.txt that tries to pull the package it from pypi.org ?)

PIP throws dependency errors for part-cad
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
partcad-cli 0.5.10 requires partcad==0.5.10, but you have partcad 0.5.11 which is incompatible.
Successfully installed partcad-0.5.11
```
and for partcad-cli
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
partcad-cli 0.5.10 requires partcad==0.5.10, but you have partcad 0.5.11 which is incompatible.
```

As expected the PartCAD client (VS Code Extensions) also throws error messages.

> Tell me if you need more details or have an idea, what is going wrong here.

**Comment by 42sol-eu** [comment]
![image](https://github.com/openvmp/partcad/assets/19718152/4fa86d9d-3bfa-4eef-ba6d-a6018e4e403b)

**Comment by openvmp** [comment]
Hi Andreas,

Could you, please, share which branch are you trying to install from?
At the moment 0.5.11 is where the `devel` branch points to.
And 0.5.10 is where the `main` branch points to.

It looks like you aretrying to install 0.5.10.
However, in both cases, it says that you already have 0.5.11 installed.
Could you, please, uninstall 0.5.11 first?

Please, show the output of

```
conda activate <env-name>
conda list | grep partcad
```

Please, note, that the VS Code extension may install the latest PartCAD in PyPI (which is now 0.5.10) in the environment currently activated in VS Code. So whatever installed 0.5.11, it's not the VS Code extension.

For troubleshooting purposes, please, share both the contents of the `Terminal View` (when `PartCAD` is selected in the dropdown in the `Terminal View`) and the contents of the `Output View` (also, when `PartCAD` is selected in the dropdown in the `Output View`).

**Comment by openvmp** [comment]
Regarding the VSCode errors, is it using the same conda environment?

**Comment by openvmp** [comment]
I'm not sure what the ask here is and I wasn't able to reproduce it.

**Comment by 42sol-eu** [comment]
@openvmp sorry. I will send you the data

**Comment by openvmp** [comment]
@42sol-eu , is there still any problem left? A lot has changed since then.

**Comment by 42sol-eu** [comment]
My first test with partcad 0.7.16 I could not reproduce this issue.

After selecting the correct Python interpreter I can use PartCAD now.
![image](https://github.com/user-attachments/assets/978d8387-a494-46fe-91a8-acce1c79a5fb)
